version: 'version 1.0.0'
services:
  discord-bot-db:
    image: postgres:14.1-alpine
    container_name: discord-bot-db
    restart: always
    user: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/discord-bot/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  discord-bot:
    image: discord-bot:latest
    container_name: discord-bot
    build:
      context: ./
      dockerfile: Dockerfile.dev
    env_file:
      - .env.dev
    depends_on:
      discord-bot-db:
        condition: service_healthy
    volumes:
      - ./src:/usr/src/app/src:z
      - ./node_modules:/usr/src/app/node_modules:z

volumes:
  db:
    driver: local