FROM node:18-alpine

WORKDIR /usr/src/app

COPY package.json ./

COPY tsconfig.json ./

RUN npm install

COPY ./ ./

RUN npx prisma generate

RUN npx prisma migrate deploy

RUN npm run build

CMD [ "npm", "start" ]
