name: Build

on:
  push:
    branches: [main]
  
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm install
      - name: Type check TypeScript
        run: npx tsc --noEmit
      - name: Build
        run: npm run build